<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 22/03/17
 * Time: 11:45 AM
 */
class LetterLink extends DataObject
{
    private static $db = array(
        'Link' => 'Varchar(100)',
    );

    private static $has_one = array(
        'LetterCategory'    =>  'LetterCategory'
    );

//    private static $summary_fields = array(
//        'ID'    =>  ''
//    );

    public function CustomPages()
    {
        $pages = Page::get();
        return $pages;
    }



    public function getCMSFields()
    {
        $fields = parent::getCMSFields();



        $link = TreeDropdownField::create('Link', 'Choose a Page', 'SiteTree');
        $fields->addFieldsToTab('Root.Main', array(
            $link
        ));

        return $fields; // TODO: Change the autogenerated stub
    }
}
