<?php

/**
 * Created by PhpStorm.
 * User: admin
 * Date: 14/03/17
 * Time: 3:46 PM
 */
class NewsLetterContent extends DataObject
{
    private static $db = array(
        'Title' => 'Varchar(100)',
        'Content' => 'Text'
    );

    private static $belongs_to = array(
        'Newsletter' => 'Newsletter.NewsLetterContent'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        return $fields; // TODO: Change the autogenerated stub
    }

    public function onBeforeWrite()
    {
        parent::onBeforeWrite(); // TODO: Change the autogenerated stub
        $content = $this->createMailChimpContent();
        $this->Content = $content;
    }

    public function ChimpService()
    {
        $chimpService = new RestfulService('https://us14.api.mailchimp.com/3.0/');
        return $chimpService;
    }

    public function createMailChimpContent()
    {
        $css = '<style>h1{ color:blue;}</style>';
        $service = $this->ChimpService();
        $service->httpHeader('Authorization: apikey b055b193339e717f0e9aa5065b24949d-us14');
        $campaign_id = $this->Newsletter()->MailChimpNewsletterID;
        $endpoint = 'campaigns/' . $campaign_id . '/content';

        $obj = new stdClass();
        $obj->html = $css . '<h1>TRON says hello AGAIn</h1><img src="http://www.imagesinspace.co.nz/site/imagesinspace/images/basic_theme/favicon.ico">';
        $data = json_encode($obj);
        $service->request($endpoint, 'PUT', $data);
    }

}
